name: CI on staging (pre-release)

on:
    push:
        branches: [staging]
    pull_request:
        branches: [staging]

jobs:
    test-and-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install Hatch
              run: pip install hatch

            - name: Build and Test All Packages
              run: |
                  set -e
                  for dir in python_modules/*; do
                    if [ -f "$dir/pyproject.toml" ]; then
                      echo "Processing $dir"
                      cd $dir
                      hatch env create
                      hatch run test
                      hatch build
                      if [ "${{ github.event_name }}" = "push" ]; then
                        HATCH_INDEX_USER="${{ secrets.TEST_PYPI_USERNAME }}" \
                        HATCH_INDEX_AUTH="${{ secrets.TEST_PYPI_PASSWORD }}" \
                        hatch publish --repo test
                      fi
                      cd - > /dev/null
                    fi
                  done
